### ISSUE TITLE
crash with 4 layers?

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#128]
If you bring up the overlay in factorio, press F12 to take a screenshot, and press shift-tab again to hide the overlay while the screenshot notification is still on screen, things crash:

```
Thread 81 "gamescope" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f87f67fc640 (LWP 219492)]
0x00007f88bc2f3f8a in radv_emit_descriptor_pointers.isra ()
from /usr/lib/libvulkan_radeon.so
(gdb) bt
#0  0x00007f88bc2f3f8a in radv_emit_descriptor_pointers.isra ()
at /usr/lib/libvulkan_radeon.so
#1  0x00007f88bc2f65f5 in radv_flush_descriptors ()
at /usr/lib/libvulkan_radeon.so
#2  0x00007f88bc2f6d7a in radv_dispatch () at /usr/lib/libvulkan_radeon.so
#3  0x00007f88bc2fc66a in radv_CmdDispatch () at /usr/lib/libvulkan_radeon.so
#4  0x00005626f315bd44 in vulkan_composite(Composite_t*, VulkanPipeline_t*, bool) (pComposite=0x7f87f67fb8a0, pPipeline=0x7f87f67fb900, bScreenshot=false)
at ../src/rendervulkan.cpp:1650
#5  0x00005626f313b390 in paint_all(Display*, MouseCursor*)
(dpy=0x7f87cc000b60, cursor=0x7f87cce0b990) at ../src/steamcompmgr.cpp:1223
#6  0x00005626f3140559 in steamcompmgr_main(int, char**)
(argc=6, argv=0x7ffff3dc68f8) at ../src/steamcompmgr.cpp:3153
#7  0x00005626f314c994 in steamCompMgrThreadRun() () at ../src/main.cpp:189
#8  0x00005626f314c4d2 in std::__invoke_impl<void, void (*)()>(std::__invoke_other, void (*&&)())
(__f=@0x5626f46982d8: 0x5626f314c979 <steamCompMgrThreadRun()>)
at /usr/include/c++/10.2.0/bits/invoke.h:60
#9  0x00005626f314c46d in std::__invoke<void (*)()>(void (*&&)())
(__fn=@0x5626f46982d8: 0x5626f314c979 <steamCompMgrThreadRun()>)
at /usr/include/c++/10.2.0/bits/invoke.h:95
#10 0x00005626f314c3f4 in std::thread::_Invoker<std::tuple<void (*)()> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x5626f46982d8)
at /usr/include/c++/10.2.0/thread:264
#11 0x00005626f314c390 in std::thread::_Invoker<std::tuple<void (*)()> >::operator()() (this=0x5626f46982d8) at /usr/include/c++/10.2.0/thread:271
#12 0x00005626f314c264 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)()> > >::_M_run() (this=0x5626f46982d0)
at /usr/include/c++/10.2.0/thread:215
#13 0x00007f894079dc24 in std::execute_native_thread_routine(void*)
(__p=0x5626f46982d0)
at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#14 0x00007f89405533e9 in start_thread () at /usr/lib/libpthread.so.0
#15 0x00007f8940481293 in clone () at /usr/lib/libc.so.6
(gdb) frame 5
#5  0x00005626f313b390 in paint_all (dpy=0x7f87cc000b60, cursor=0x7f87cce0b990)
at ../src/steamcompmgr.cpp:1223
1223                    bool bResult = vulkan_composite( &composite, &pipeline, takeScreenshot );
(gdb) p composite
$1 = {nLayerCount = 4, nSwapChannels = 0, data = {layers = {{
flScaleX = 0.949999988, flScaleY = 0.949999988, flOffsetX = 0.5,
flOffsetY = -13.5, flOpacity = 1}, {flScaleX = 1.5, flScaleY = 1.5,
flOffsetX = 0.5, flOffsetY = 0.5, flOpacity = 0.999991953}, {
flScaleX = 1.5, flScaleY = 1.5, flOffsetX = -846.5,
flOffsetY = -586.5, flOpacity = 1}, {flScaleX = 1, flScaleY = 1,
flOffsetX = -577.763184, flOffsetY = -375.973694, flOpacity = 1}}}}
(gdb) p pipeline
$2 = {layerBindings = {{surfaceWidth = 1216, surfaceHeight = 656, tex = 2684,
fbid = 0, zpos = 0, bFilter = true, bBlackBorder = true}, {
surfaceWidth = 1920, surfaceHeight = 1080, tex = 2685, fbid = 0,
zpos = 1, bFilter = true, bBlackBorder = true}, {surfaceWidth = 650,
surfaceHeight = 200, tex = 2686, fbid = 0, zpos = 1, bFilter = true,
bBlackBorder = false}, {surfaceWidth = 16, surfaceHeight = 16,
tex = 2688, fbid = 0, zpos = 2, bFilter = false, bBlackBorder = false}}}
(gdb) quit
A debugging session is active.

Inferior 1 [process 219292] will be detached.

Quit anyway? (y or n) y
Detaching from program: /home/plagman/src/gamescope/build/gamescope, process 219292
[Inferior 1 (process 219292) detached]
```

The cursor is shown again as the overlay starts fading out, so that's a total of 4 layers being composited.

**Comment by Plagman** [comment]
Was regression from spec constant change by @Joshua-Ashton, fixed.
