### ISSUE TITLE
Gamescope Crashing when Run Through Steam Launch Options

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [Plagman/gamescope#225]
I've gotten gamescope running from source on my system, which I confirmed by running `gamescope -- glxgears` and it seemed to work correctly.

I then played Dark Souls III by adding the gamescope command to the launch options (i.e. `gamescope -- %command%`) and it launched correctly. I played for around 30 minutes, and then closed the program to add mangohud to track performance.

I installed mangohud and ran `gamescope -- mangohud %command%`, which then failed to boot. I decided to try running mangohud through the terminal by running `gamescope -- mangohud glxgears` and `gamescope -- mangohud vkcube` and both worked as expected.

I then went back to steam and tried removing mangohud and booting into the game with just gamescope (`gamescope -- %command%`) and it still failed to launch. As of writing this post, I simply cannot run any games through my steam client with gamescope even though it works fine outside of steam.

Running `coredumpctl gdb` after one attempt to launch the game via steam resulted in the following backtrace.

```
#0  0x00007f3918d06d36 in  () at /home/eoin/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so
#1  0x00007f3918d0e391 in  () at /home/eoin/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so
#2  0x00007f3918d1ee5e in XEventsQueued () at /home/eoin/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so
#3  0x00007f3918a33903 in  () at /usr/lib/libSDL2-2.0.so.0
#4  0x00007f391899057e in  () at /usr/lib/libSDL2-2.0.so.0
#5  0x00007f3918990609 in  () at /usr/lib/libSDL2-2.0.so.0
#6  0x000055769724fcdb in inputSDLThreadRun() () at ../src/sdlwindow.cpp:123
        event = 
          {type = 0, common = {type = 0, timestamp = 0}, display = {type = 0, timestamp = 0, display = 2548240632, event = 118 'v', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 374233904}, window = {type = 0, timestamp = 0, windowID = 2548240632, event = 118 'v', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 374233904, data2 = 32569}, key = {type = 0, timestamp = 0, windowID = 2548240632, state = 118 'v', repeat = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = 374233904, sym = 32569, mod = 20448, unused = 21878}}, edit = {type = 0, timestamp = 0, windowID = 2548240632, text = "vU\000\000\060[N\026\071\177\000\000\340O#\227vU\000\000\000\000\000\000\000\000\000\000\370", <incomplete sequence \343\227>, start = 21878, length = 374233936}, text = {type = 0, timestamp = 0, windowID = 2548240632, text = "vU\000\000\060[N\026\071\177\000\000\340O#\227vU\000\000\000\000\000\000\000\000\000\000\370", <incomplete sequence \343\227>}, motion = {type = 0, timestamp = 0, windowID = 2548240632, which = 21878, state = 374233904, x = 32569, y = -1759293472, xrel = 21878, yrel = 0}, button = {type = 0, timestamp = 0, windowID = 2548240632, which = 21878, button = 48 '0', state = 91 '[', clicks = 78 'N', padding1 = 22 '\026', x = 32569, y = -1759293472}, wheel = {type = 0, timestamp = 0, windowID = 2548240632, which = 21878, x = 374233904, y = 32569, direction = 2535673824}, jaxis = {type = 0, timestamp = 0, which = -1746726664, axis = 118 'v', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', value = 23344, padding4 = 5710}, jball = {type = 0, timestamp = 0, which = -1746726664, ball = 118 'v', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 23344, yrel = 5710}, jhat = {type = 0, timestamp = 0, which = -1746726664, hat = 118 'v', value = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 0, timestamp = 0, which = -1746726664, button = 118 'v', state = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 0, timestamp = 0, which = -1746726664}, caxis = {type = 0, timestamp = 0, which = -1746726664, axis = 118 'v', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', value = 23344, padding4 = 5710}, cbutton = {type = 0, timestamp = 0, which = -1746726664, button = 118 'v', state = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 0, timestamp = 0, which = -1746726664}, ctouchpad = {type = 0, timestamp = 0, which = -1746726664, touchpad = 21878, finger = 374233904, x = 4.56388897e-41, y = -5.2768957e-25, pressure = 3.06576078e-41}, csensor = {type = 0, timestamp = 0, which = -1746726664, sensor = 21878, data = {1.66693212e-25, 4.56388897e-41, -5.2768957e-25}}, adevice = {type = 0, timestamp = 0, which = 2548240632, iscapture = 118 'v', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000'}, sensor = {type = 0, timestamp = 0, which = -1746726664, data = {3.06576078e-41, 1.66693212e-25, 4.56388897e-41, -5.2768957e-25, 3.06576078e-41, 0}}, quit = {type = 0, timestamp = 0}, user = {type = 0, timestamp = 0, windowID = 2548240632, code = 21878, data1 = 0x7f39164e5b30, data2 = 0x557697234fe0 <std::_Tuple_impl<0ul, void (*)()>::_M_head(std::_Tuple_impl<0ul, void (*)()>&)+24>}, syswm = {type = 0, timestamp = 0, msg = 0x557697e310f8}, tfinger = {type = 0, timestamp = 0, touchId = 93967842742520, fingerId = 139883164097328, x = -5.2768957e-25, y = 3.06576078e-41, dx = 0, dy = 0, pressure = -1.46738147e-24, windowID = 21878}, mgesture = {type = 0, timestamp = 0, touchId = 93967842742520, dTheta = 1.66693212e-25, dDist = 4.56388897e-41, x = -5.2768957e-25, y = 3.06576078e-41, numFingers = 0, padding = 0}, dgesture = {type = 0, timestamp = 0, touchId = 93967842742520, gestureId = 139883164097328, numFingers = 2535673824, error = 3.06576078e-41, x = 0, y = 0}, drop = {type = 0, timestamp = 0, file = 0x557697e310f8 "\251\370$\227vU", windowID = 374233904}, padding = "\000\000\000\000\000\000\000\000\370\020\343\227vU\000\000\060[N\026\071\177\000\000\340O#\227vU\000\000\000\000\000\000\000\000\000\000\370\020\343\227vU\000\000P[N\026\071\177\000"}
        mod = KMOD_NONE
        key = 0
        nSDLWindowFlags = 268435496
        extCount = 2
#7  0x0000557697234fab in std::__invoke_impl<void, void (*)()>(std::__invoke_other, void (*&&)()) (__f=@0x557697e310f8: 0x55769724f8a9 <inputSDLThreadRun()>) at /usr/include/c++/11.1.0/bits/invoke.h:61
#8  0x0000557697234f55 in std::__invoke<void (*)()>(void (*&&)()) (__fn=@0x557697e310f8: 0x55769724f8a9 <inputSDLThreadRun()>) at /usr/include/c++/11.1.0/bits/invoke.h:96
#9  0x0000557697234f02 in std::thread::_Invoker<std::tuple<void (*)()> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x557697e310f8) at /usr/include/c++/11.1.0/bits/std_thread.h:253
#10 0x0000557697234ed6 in std::thread::_Invoker<std::tuple<void (*)()> >::operator()() (this=0x557697e310f8) at /usr/include/c++/11.1.0/bits/std_thread.h:260
#11 0x0000557697234e32 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)()> > >::_M_run() (this=0x557697e310f0) at /usr/include/c++/11.1.0/bits/std_thread.h:211
#12 0x00007f39184cb3c4 in std::execute_native_thread_routine(void*) (__p=0x557697e310f0) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:82
#13 0x00007f391827f259 in start_thread () at /usr/lib/libpthread.so.0
#14 0x00007f39181a85e3 in clone () at /usr/lib/libc.so.6

```

This allowed me to notice that it was crashing on a call within `gameoverlayrenderer.so`. Trying to disable the overlay via the steam game properties window did not resolve this crash.

Here's the system configuration in question:

```
 OS: Manjaro 21.1.0 Pahvo
 Kernel: x86_64 Linux 5.10.53-1-MANJARO
 Shell: bash 5.1.8
 Resolution: 3120x1920
 DE: KDE 5.84.0 / Plasma 5.22.4
 WM: KWin
 GTK Theme: Breath [GTK2/3]
 Icon Theme: breath2
 Disk: 166G / 3.5T (5%)
 CPU: AMD Ryzen 7 5800X 8-Core @ 16x 3.8GHz
 GPU: Radeon RX 590 Series (POLARIS10, DRM 3.40.0, 5.10.53-1-MANJARO, LLVM 12.0.1)
 RAM: 2879MiB / 32090MiB
```

Thanks!

**Comment by Eoin-ONeill-Yokai** [comment]
Ah, It looks like this is a duplicate of #224 . I will close this.
