### ISSUE TITLE
Certain game crashing only when not using gdb

### ISSUE THREAD

**Issue by BrianAllred** [Plagman/gamescope#281]
Not naming the game publicly because the developers are actively hostile to Linux users. Can reveal via private comms.

Gamescope crashes when entering [game] after the login screen, but *only* when not using gdb, so I can't grab a stacktrace. Tried both `gamescope` and `gamescope-git` packages from the AUR, as well as building 3.9.2 and master locally, behavior is identical between all versions.

Error message:
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  10 (X_UnmapWindow)
  Resource id in failed request:  0x5600001
  Serial number of failed request:  14571
  Current serial number in output stream:  14574
xwm: error 3: BadWindow (invalid Window parameter) request 15 minor 0 serial 202251
xwm: error 3: BadWindow (invalid Window parameter) request 41 minor 0 serial 202264
pipewire: renegociating stream params (size: 2560x1372)
gamescope: received kill signal, terminating!
(EE) failed to read Wayland events: Broken pipe
```

Env:
* ArchLinux
* AMD Ryzen 5800X
* AMD Radeon 6800XT
* 64 GB RAM
* Wayland on Gnome 40
* Mesa 21.2.3

**Comment by BrianAllred** [comment]
Update: crash happened while running under gdb, so it appears to happen every now and then, but not often.

Error message:

```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  10 (X_UnmapWindow)
  Resource id in failed request:  0x4e00001
  Serial number of failed request:  13523
  Current serial number in output stream:  13526
xwm: error 3: BadWindow (invalid Window parameter) request 15 minor 0 serial 231165
xwm: error 3: BadWindow (invalid Window parameter) request 41 minor 0 serial 231178
```

Full back trace:

```
(gdb) bt full
#0  0x00007ffff74b1b2f in poll () at /usr/lib/libc.so.6
#1  0x000055555558ce8a in poll (__timeout=-1, __nfds=1, __fds=0x7fffffffe480)
    at /usr/include/bits/poll2.h:47
        ret = <optimized out>
        pollfd = {fd = 4, events = 1, revents = 0}
#2  wlserver_run() () at ../gamescope-3.9.2/src/wlserver.cpp:760
        ret = <optimized out>
        pollfd = {fd = 4, events = 1, revents = 0}
#3  0x000055555556925f in main(int, char**)
    (argc=<optimized out>, argv=0x7fffffffe4d0)
    at ../gamescope-3.9.2/src/main.cpp:385
        nPreferredOutputWidth = <optimized out>
        nPreferredOutputHeight = 1440
        optstring = "w:h:r:m:iW:H:no:bfO:R:T:C:vecx"
        o = <optimized out>
        opt_index = -1
        caps = <optimized out>
        steamCompMgrThread = {_M_id = {_M_thread = 140735524771392}}
```
