### ISSUE TITLE
Segfault on exit

### ISSUE THREAD

**Issue by emersion** [Plagman/gamescope#46]
```
==590402==ERROR: AddressSanitizer: attempting double-free on 0x610000050540 in thread T40:
X connection to :1 broken (explicit kill or server shutdown).
    #0 0x7f334a311720 in __interceptor_free /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:122
    #1 0x7f334429ae39  (/usr/lib/dri/radeonsi_dri.so+0xb47e39)
    #2 0x7f3348aef536 in __run_exit_handlers (/usr/lib/libc.so.6+0x3e536)
    #3 0x7f3348aef6ed in exit (/usr/lib/libc.so.6+0x3e6ed)
    #4 0x7f334a0bb3f1 in _XDefaultIOError (/usr/lib/libX11.so.6+0x433f1)
    #5 0x7f334a0bb69d in _XIOError (/usr/lib/libX11.so.6+0x4369d)
    #6 0x7f334a0b901e in _XReadEvents (/usr/lib/libX11.so.6+0x4101e)
    #7 0x7f334a0a7c98 in XNextEvent (/usr/lib/libX11.so.6+0x2fc98)
    #8 0x561ee62212dd in steamcompmgr_main ../src/steamcompmgr.cpp:2267
    #9 0x561ee624e9ab in steamCompMgrThreadRun() ../src/main.cpp:121
    #10 0x561ee624e41d in void std::__invoke_impl<void, void (*)()>(std::__invoke_other, void (*&&)()) /usr/include/c++/9.3.0/bits/invoke.h:60
    #11 0x561ee624e283 in std::__invoke_result<void (*)()>::type std::__invoke<void (*)()>(void (*&&)()) /usr/include/c++/9.3.0/bits/invoke.h:95
    #12 0x561ee624e0e7 in void std::thread::_Invoker<std::tuple<void (*)()> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/9.3.0/thread:244
    #13 0x561ee624dfe2 in std::thread::_Invoker<std::tuple<void (*)()> >::operator()() /usr/include/c++/9.3.0/thread:251
    #14 0x561ee624d7ee in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)()> > >::_M_run() /usr/include/c++/9.3.0/thread:195
    #15 0x7f3349833b23 in execute_native_thread_routine /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
    #16 0x7f3348c8046e in start_thread (/usr/lib/libpthread.so.0+0x946e)
    #17 0x7f3348bb03d2 in clone (/usr/lib/libc.so.6+0xff3d2)

0x610000050540 is located 0 bytes inside of 184-byte region [0x610000050540,0x6100000505f8)
freed by thread T0 here:
    #0 0x7f334a311720 in __interceptor_free /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:122
    #1 0x7f334429ae39  (/usr/lib/dri/radeonsi_dri.so+0xb47e39)

previously allocated by thread T0 here:
    #0 0x7f334a311b3a in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f33442a101d  (/usr/lib/dri/radeonsi_dri.so+0xb4e01d)

Thread T40 created by T0 here:
    #0 0x7f334a23b377 in __interceptor_pthread_create /build/gcc/src/gcc/libsanitizer/asan/asan_interceptors.cc:208
    #1 0x7f3349833df9 in __gthread_create /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:663
    #2 0x7f3349833df9 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:135
    #3 0x561ee624ea44 in startSteamCompMgr ../src/main.cpp:126
    #4 0x561ee6255d2f in xwayland_ready ../src/wlserver.c:119
    #5 0x561ee639e1c5 in wlr_signal_emit_safe ../subprojects/wlroots/util/signal.c:29
    #6 0x561ee62b599f in xserver_handle_ready ../subprojects/wlroots/xwayland/xwayland.c:251
    #7 0x7f3349f71434  (/usr/lib/libwayland-server.so.0+0xa434)
    #8 0x7ffda7c84daf  ([stack]+0x1ddaf)
```

**Comment by Plagman** [comment]
At least part of it will involve putting an X error handler in the side threads that have an X display, I think.
