### ISSUE TITLE
Fails to create window on NVIDIA

### ISSUE THREAD

**Issue by tjhexf** [Plagman/gamescope#816]
Log:

```
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
wlserver: [backend/headless/backend.c:68] Creating headless backend
vulkan: selecting physical device 'NVIDIA GeForce GTX 970': queue family 0
vulkan: physical device supports DRM format modifiers
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x3231564E (VkResult: 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:16] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/server.c:108] Starting Xwayland on :1
wlserver: [types/wlr_compositor.c:673] New wlr_surface 0x55cc329f1520 (res 0x55cc329f6d40)
wlserver: [xwayland/server.c:273] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 80
pipewire: renegotiating stream params (size: 1280x720)
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0108:fixme:nstc:NSTC2_fnSetControlStyle2 mask & style (0x00000004) contains unsupported style(s): 0x00000004
src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

0108:fixme:shell:IShellBrowser_fnSendControlMsg stub, 007BBF90 (2, 1026, a003, 0, 0068F56C)
0108:fixme:shell:IShellBrowser_fnSendControlMsg stub, 007BBF90 (2, 1026, a004, 1, 0068F56C)
0108:fixme:shell:IShellBrowser_fnSendControlMsg stub, 007BBF90 (2, 1025, a003, 1, 0068F56C)
0108:fixme:shell:IShellBrowser_fnSendControlMsg stub, 007BBF90 (2, 1025, a004, 1, 0068F56C)
xwm: Unhandled client message: _NET_STARTUP_INFO_BEGIN
xwm: Unhandled client message: _NET_STARTUP_INFO
xwm: Unhandled client message: _NET_STARTUP_INFO
src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

wlserver: [types/wlr_compositor.c:673] New wlr_surface 0x55cc328e2dc0 (res 0x55cc329fa460)
src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

006c:fixme:imm:ImeSetActiveContext (0000000000010026, 0): stub
006c:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000010026): stub
0108:fixme:imm:ImeSetActiveContext (00020048, 1): stub
0108:fixme:imm:ImmReleaseContext (00010052, 00020048): stub
src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Error getting buffer
src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)
```

**Comment by tjhexf** [comment]
By the way, all vulkan software seems to work outside of gamescope. Dxvk and vkd3d on wine both run without issues

**Comment by tjhexf** [comment]
Edit: Nvidia-beta drivers seem to give a different error:

```
~ gamescope -- wine explorer
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
wlserver: [backend/headless/backend.c:68] Creating headless backend
vulkan: selecting physical device 'NVIDIA GeForce GTX 970': queue family 0
vulkan: physical device supports DRM format modifiers
vulkan: vkCreateDevice failed (VkResult: -7)
Failed to initialize Vulkan
```

**Comment by tjhexf** [comment]
Update: Logs had more things after nvidia driver update

```src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

wlserver: [types/wlr_compositor.c:673] New wlr_surface 0x55ac29a63210 (res 0x55ac29b77530)
src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Error getting buffer
QString::contains: invalid QRegularExpression object
QString::contains: invalid QRegularExpression object
QString::contains: invalid QRegularExpression object
QString::contains: invalid QRegularExpression object
QString::contains: invalid QRegularExpression object
QString::contains: invalid QRegularExpression object
QString::contains: invalid QRegularExpression object
QString::contains: invalid QRegularExpression object
QString::contains: invalid QRegularExpression object
QString::contains: invalid QRegularExpression object
QString::contains: invalid QRegularExpression object
QString::contains: invalid QRegularExpression object
QString::contains: invalid QRegularExpression object```

**Comment by tjhexf** [comment]
Still active. Logs after nvidia upgrade:

```
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
wlserver: [backend/headless/backend.c:68] Creating headless backend
vulkan: selecting physical device 'NVIDIA GeForce GTX 970': queue family 0
vulkan: physical device supports DRM format modifiers
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x3231564E (VkResult: 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:16] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/server.c:108] Starting Xwayland on :1
wlserver: [types/wlr_compositor.c:673] New wlr_surface 0x562b99d05a40 (res 0x562b99d0b260)
wlserver: [xwayland/server.c:273] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 80
pipewire: renegotiating stream params (size: 1280x720)
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0108:fixme:nstc:NSTC2_fnSetControlStyle2 mask & style (0x00000004) contains unsupported style(s): 0x00000004
src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

0108:fixme:shell:IShellBrowser_fnSendControlMsg stub, 007BC080 (2, 1026, a003, 0, 0068F56C)
0108:fixme:shell:IShellBrowser_fnSendControlMsg stub, 007BC080 (2, 1026, a004, 1, 0068F56C)
0108:fixme:shell:IShellBrowser_fnSendControlMsg stub, 007BC080 (2, 1025, a003, 1, 0068F56C)
0108:fixme:shell:IShellBrowser_fnSendControlMsg stub, 007BC080 (2, 1025, a004, 1, 0068F56C)
xwm: Unhandled client message: _NET_STARTUP_INFO_BEGIN
xwm: Unhandled client message: _NET_STARTUP_INFO
xwm: Unhandled client message: _NET_STARTUP_INFO
src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

wlserver: [types/wlr_compositor.c:673] New wlr_surface 0x562b99bf7500 (res 0x562b99d0e980)
src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

006c:fixme:imm:ImeSetActiveContext (0000000000010026, 0): stub
006c:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000010026): stub
0108:fixme:imm:ImeSetActiveContext (00020048, 1): stub
0108:fixme:imm:ImmReleaseContext (00010052, 00020048): stub
src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Error getting buffer
src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)
```
(wine explorer with gamescope)

**Comment by Sweeper5** [comment]
I just tested this on my Arch Linux install with a 2080 Ti using the latest Nvidia drivers.
And my behaviour I see is that the window initially renders and then freezes.
So running a command like gamescope -w 1600 -h 1050 -i wine explorer

Will cause it to freeze as well, all I get to see is the static image of the file explorer and thats it, no interaction with the window is possible at all, and I have to CTRL + C to stop it in the terminal window.
Output there is:
```
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
wlserver: [backend/headless/backend.c:68] Creating headless backend
vulkan: selecting physical device 'NVIDIA GeForce RTX 2080 Ti': queue family 2
vulkan: physical device supports DRM format modifiers
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x3231564E (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x48344241 (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x38344241 (VkResult: 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   AR24 (0x34325241)
vulkan:   XR24 (0x34325258)
vulkan:   AB24 (0x34324241)
vulkan:   XB24 (0x34324258)
vulkan:   AB30 (0x30334241)
vulkan:   XB30 (0x30334258)
vulkan:   AR30 (0x30335241)
vulkan:   XR30 (0x30335258)
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:16] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/server.c:108] Starting Xwayland on :1
wlserver: [types/wlr_compositor.c:681] New wlr_surface 0x556823c58d00 (res 0x5568240a4ab0)
wlserver: [xwayland/server.c:273] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 193
002c:fixme:winediag:LdrInitializeThunk wine-staging 8.5 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
pipewire: renegotiating stream params (size: 1280x720)
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
0084:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
0084:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
0084:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0124:fixme:nstc:NSTC2_fnSetControlStyle2 mask & style (0x00000004) contains unsupported style(s): 0x00000004
0124:fixme:shell:IShellBrowser_fnSendControlMsg stub, 008B85B0 (2, 1026, a003, 0, 0078F56C)
0124:fixme:shell:IShellBrowser_fnSendControlMsg stub, 008B85B0 (2, 1026, a004, 1, 0078F56C)
0124:fixme:shell:IShellBrowser_fnSendControlMsg stub, 008B85B0 (2, 1025, a003, 1, 0078F56C)
0124:fixme:shell:IShellBrowser_fnSendControlMsg stub, 008B85B0 (2, 1025, a004, 1, 0078F56C)
wlserver: [types/wlr_compositor.c:681] New wlr_surface 0x556823f5fd30 (res 0x5568240a9530)
0124:fixme:imm:ImeSetActiveContext himc 0002005E, flag 0x1 stub!
0074:fixme:imm:ImeSetActiveContext himc 0000000000010026, flag 0 stub!
0124:fixme:imm:ImmReleaseContext (00010062, 0002005E): stub
0074:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000010026): stub
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
^Cgamescope: received kill signal, terminating!
xwm: Lost connection to the X11 server 0
xwm: X11 I/O error
0150:fixme:console:default_ctrl_handler Terminating process 120 on event 0
X connection to :1 broken (explicit kill or server shutdown).
wine client error:124: write: Bad file descriptor 
```

**Comment by surafel911** [comment]
@tjhexf your issue might be related to #704 and #708. Have you tried adding `nvidia-drm.modeset=1` to your kernel parameters and following the instructions in [this thread](https://github.com/ValveSoftware/gamescope/issues/708#issuecomment-1430397743).

@Sweeper5 Try running gamescope with the same conditions using `gdb`. If it hangs and you need to ctrl+c, copy the full back trace from GDB here.

**Comment by Sweeper5** [comment]
Sorry for the late reply, but I did do a run with gdb and didn't get a window, however I did get a different output.
There have been a few updates since then, but in general it behaves very similarly in the sense that the window appears frozen, it will start blinking the wine explorer if you right click in it, but you do not get to browse or see the context menu appear.

GDB tracelog from running the command "gdb -ex=r --args gamescope -w 1600 -h 1050 -i wine explorer"
```
GNU gdb (GDB) 13.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from gamescope...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
(No debugging symbols found in gamescope)                                                                                    
Starting program: /usr/bin/gamescope -w 1600 -h 1050 -i wine explorer
[Thread debugging using libthread_db enabled]                                                                                
Using host libthread_db library "/usr/lib/libthread_db.so.1".
No CAP_SYS_NICE, falling back to regular-priority compute and threads.                                                       
Performance will be affected.
wlserver: [backend/headless/backend.c:68] Creating headless backend
vulkan: selecting physical device 'NVIDIA GeForce RTX 2080 Ti': queue family 2                                               
vulkan: physical device supports DRM format modifiers
[New Thread 0x7ffff15ff6c0 (LWP 53712)]
[New Thread 0x7ffff0dfe6c0 (LWP 53713)]
[New Thread 0x7fffebfff6c0 (LWP 53714)]
[New Thread 0x7fffeb7fe6c0 (LWP 53715)]
[New Thread 0x7fffeacfd6c0 (LWP 53716)]
[New Thread 0x7fffea4fc6c0 (LWP 53717)]
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x3231564E (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x48344241 (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x38344241 (VkResult: 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   AR24 (0x34325241)
vulkan:   XR24 (0x34325258)
vulkan:   AB24 (0x34324241)
vulkan:   XB24 (0x34324258)
vulkan:   AB30 (0x30334241)
vulkan:   XB30 (0x30334258)
vulkan:   AR30 (0x30335241)
vulkan:   XR30 (0x30335258)
wlserver: Running compositor on wayland display 'gamescope-0'                                                                
wlserver: [backend/headless/backend.c:16] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
[Detaching after fork from child process 53718]
wlserver: [xwayland/server.c:108] Starting Xwayland on :1
[Thread 0x7fffeacfd6c0 (LWP 53716) exited]
wlserver: wl_event_loop_dispatch failed

Failed to initialize wlserver
[Thread 0x7fffeb7fe6c0 (LWP 53715) exited]
[Thread 0x7ffff15ff6c0 (LWP 53712) exited]
(EE) could not connect to wayland server
[Thread 0x7fffea4fc6c0 (LWP 53717) exited]
[Thread 0x7fffebfff6c0 (LWP 53714) exited]
[Thread 0x7ffff0dfe6c0 (LWP 53713) exited]
[Inferior 1 (process 53709) exited with code 01]
(gdb) run
Starting program: /usr/bin/gamescope -w 1600 -h 1050 -i wine explorer
[Thread debugging using libthread_db enabled]                                                                                
Using host libthread_db library "/usr/lib/libthread_db.so.1".
No CAP_SYS_NICE, falling back to regular-priority compute and threads.                                                       
Performance will be affected.
wlserver: [backend/headless/backend.c:68] Creating headless backend
vulkan: selecting physical device 'NVIDIA GeForce RTX 2080 Ti': queue family 2                                               
vulkan: physical device supports DRM format modifiers
[New Thread 0x7ffff15ff6c0 (LWP 53911)]
[New Thread 0x7ffff0dfe6c0 (LWP 53912)]
[New Thread 0x7fffebfff6c0 (LWP 53913)]
[New Thread 0x7fffeb7fe6c0 (LWP 53914)]
[New Thread 0x7fffeacfd6c0 (LWP 53915)]
[New Thread 0x7fffea4fc6c0 (LWP 53916)]
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x3231564E (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x48344241 (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x38344241 (VkResult: 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   AR24 (0x34325241)
vulkan:   XR24 (0x34325258)
vulkan:   AB24 (0x34324241)
vulkan:   XB24 (0x34324258)
vulkan:   AB30 (0x30334241)
vulkan:   XB30 (0x30334258)
vulkan:   AR30 (0x30335241)
vulkan:   XR30 (0x30335258)
wlserver: Running compositor on wayland display 'gamescope-0'                                                                
wlserver: [backend/headless/backend.c:16] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
[Detaching after fork from child process 53917]
wlserver: [xwayland/server.c:108] Starting Xwayland on :1
wlserver: wl_event_loop_dispatch failed

Failed to initialize wlserver
[Thread 0x7fffeb7fe6c0 (LWP 53914) exited]
[Thread 0x7ffff15ff6c0 (LWP 53911) exited]

Thread 6 "gamescope-shdr" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeacfd6c0 (LWP 53915)]
0x00005555555a0468 in ?? ()
(gdb) (EE) could not connect to wayland server
```

**Comment by surafel911** [comment]
@Sweeper5 what does the backtrace say when you run the app?

**Comment by surafel911** [comment]
@Sweeper5 If you could try one more time I'd appreciate it. This time give a back trace? I am on version3.11.52 and I do not have this issue on my system.

**Comment by AlexFolland** [comment]
I have a Manjaro system with Nvidia driver version 535.54.03-1 using an Nvidia GTX 1080 Ti.  I am using XFWM 4.16 as my window manager.  I am trying to run retroarch with the vulkan renderer in a gamescope session in fullscreen, but it fails.  If I use `--borderless`, it works (but is behind my XFCE panels), but omitting `--borderless` causes gamescope to generate artifacts and freeze, causing the entire screen to become non-interactive and non-updating.  The only way out is to kill the game running in the gamescope process using an xkill keybind, then manually kill the `gamescope-wl` process from ksysguard.  Here is output when using GDB and getting a backtrace.  Please click to expand the output below and see the command that I am using.

<details><summary>GDB command and terminal output</summary>

```Plaintext
[alex@alex-pc ~]$ gdb -ex=r --args gamescope --fullscreen -w 1920 -h 1200 -W 1920 -H 1200 -- retroarch --verbose
GNU gdb (GDB) 13.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from gamescope...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for /usr/bin/gamescope
                                                                                --Type <RET> for more, q to quit, c to continue without paging--
(No debugging symbols found in gamescope)
Starting program: /usr/bin/gamescope --fullscreen -w 1920 -h 1200 -W 1920 -H 1200 -- retroarch --verbose
Downloading separate debug info for /lib64/ld-linux-x86-64.so.2
Downloading separate debug info for system-supplied DSO at 0x7ffff7fc8000       
Downloading separate debug info for /usr/lib/libX11.so.6                        
Downloading separate debug info for /usr/lib/libXdamage.so.1                    
Downloading separate debug info for /usr/lib/libXfixes.so.3                     
Downloading separate debug info for /usr/lib/libXcomposite.so.1                 
Downloading separate debug info for /usr/lib/libXrender.so.1                    
Downloading separate debug info for /usr/lib/libXext.so.6                       
Downloading separate debug info for /usr/lib/libXxf86vm.so.1                    
Downloading separate debug info for /usr/lib/libXRes.so.1                       
Downloading separate debug info for /usr/lib/libdrm.so.2                        
Downloading separate debug info for /usr/lib/libwayland-server.so.0             
Downloading separate debug info for /usr/lib/libxkbcommon.so.0                  
Downloading separate debug info for /usr/lib/libSDL2-2.0.so.0                   
Downloading separate debug info for /usr/lib/libwlroots.so.11                   
Downloading separate debug info for /usr/lib/libvulkan.so.1                     
Downloading separate debug info for /usr/lib/libliftoff.so.0                    
Downloading separate debug info for /usr/lib/libXtst.so.6                       
Downloading separate debug info for /usr/lib/libcap.so.2                        
Downloading separate debug info for /usr/lib/libpipewire-0.3.so.0               
Downloading separate debug info for /usr/lib/libm.so.6                          
Downloading separate debug info for /usr/lib/libc.so.6                          
[Thread debugging using libthread_db enabled]                                   
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Downloading separate debug info for /usr/lib/libxcb.so.1
Downloading separate debug info for /usr/lib/libffi.so.8                        
Downloading separate debug info for /usr/lib/libudev.so.1                       
Downloading separate debug info for /usr/lib/libpixman-1.so.0                   
Downloading separate debug info for /usr/lib/libEGL.so.1                        
Downloading separate debug info for /usr/lib/libgbm.so.1                        
Downloading separate debug info for /usr/lib/libGLESv2.so.2                     
Downloading separate debug info for /usr/lib/libinput.so.10                     
Downloading separate debug info for /usr/lib/libxcb-dri3.so.0                   
Downloading separate debug info for /usr/lib/libxcb-present.so.0                
Downloading separate debug info for /usr/lib/libxcb-render.so.0                 
Downloading separate debug info for /usr/lib/libxcb-render-util.so.0            
Downloading separate debug info for /usr/lib/libxcb-shm.so.0                    
Downloading separate debug info for /usr/lib/libxcb-xfixes.so.0                 
Downloading separate debug info for /usr/lib/libxcb-xinput.so.0                 
Downloading separate debug info for /usr/lib/libwayland-client.so.0             
Downloading separate debug info for /usr/lib/libseat.so.1                       
Downloading separate debug info for /usr/lib/libxcb-composite.so.0              
Downloading separate debug info for /usr/lib/libxcb-icccm.so.4                  
Downloading separate debug info for /usr/lib/libxcb-res.so.0                    
Downloading separate debug info for /usr/lib/libxcb-errors.so.0                 
Downloading separate debug info for /usr/lib/libXau.so.6                        
Downloading separate debug info for /usr/lib/libXdmcp.so.6                      
Downloading separate debug info for /usr/lib/libGLdispatch.so.0                 
Downloading separate debug info for /usr/lib/libexpat.so.1                      
Downloading separate debug info for /usr/lib/libxcb-randr.so.0                  
Downloading separate debug info for /usr/lib/libmtdev.so.1                      
Downloading separate debug info for /usr/lib/libevdev.so.2                      
Downloading separate debug info for /usr/lib/libwacom.so.9                      
Downloading separate debug info for /usr/lib/libsystemd.so.0                    
Downloading separate debug info for /usr/lib/libgudev-1.0.so.0                  
Downloading separate debug info for /usr/lib/libgobject-2.0.so.0                
Downloading separate debug info for /usr/lib/libglib-2.0.so.0                   
Downloading separate debug info for /usr/lib/libgcrypt.so.20                    
Downloading separate debug info for /usr/lib/liblzma.so.5                       
Downloading separate debug info for /usr/lib/libzstd.so.1                       
Downloading separate debug info for /usr/lib/liblz4.so.1                        
Downloading separate debug info for /usr/lib/libpcre2-8.so.0                    
Downloading separate debug info for /usr/lib/libgpg-error.so.0                  
No CAP_SYS_NICE, falling back to regular-priority compute and threads.          
Performance will be affected.
wlserver: [backend/headless/backend.c:68] Creating headless backend
Downloading separate debug info for /usr/lib/libdbus-1.so.3
Downloading separate debug info for /usr/lib/libXcursor.so.1                    
Downloading separate debug info for /usr/lib/libXi.so.6                         
Downloading separate debug info for /usr/lib/libXrandr.so.2                     
Downloading separate debug info for /usr/lib/libXss.so.1                        
Downloading separate debug info for /usr/lib/libGLX_nvidia.so.0                 
Downloading separate debug info for /usr/lib/libnvidia-glsi.so.535.54.03        
Downloading separate debug info for /usr/lib/libnvidia-tls.so.535.54.03         
Downloading separate debug info for /usr/lib/libnvidia-glcore.so.535.54.03      
Downloading separate debug info for /usr/lib/libdl.so.2                         
Downloading separate debug info for /usr/lib/libpthread.so.0                    
Downloading separate debug info for /usr/lib/librt.so.1                         
Downloading separate debug info for /usr/lib/libnvidia-glvkspirv.so.535.54.03   
Downloading separate debug info for /usr/lib/libX11-xcb.so.1                    
Downloading separate debug info for /usr/lib/libxcb-glx.so.0                    
vulkan: selecting physical device 'NVIDIA GeForce GTX 1080 Ti': queue family 2  
vulkan: physical device supports DRM format modifiers
[New Thread 0x7ffff05ff6c0 (LWP 35449)]
[New Thread 0x7fffefdfe6c0 (LWP 35450)]
[New Thread 0x7fffef5fd6c0 (LWP 35451)]
[New Thread 0x7fffee97c6c0 (LWP 35452)]
[New Thread 0x7fffede7b6c0 (LWP 35453)]
[New Thread 0x7fffed67a6c0 (LWP 35454)]
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x3231564E (VkResult: 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
wlserver: Running compositor on wayland display 'gamescope-0'                   
wlserver: [backend/headless/backend.c:16] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
[Detaching after fork from child process 35455]
wlserver: [xwayland/server.c:108] Starting Xwayland on :1
wlserver: wl_event_loop_dispatch failed

Failed to initialize wlserver
[Thread 0x7ffff05ff6c0 (LWP 35449) exited]
[Thread 0x7fffee97c6c0 (LWP 35452) exited]

Thread 6 "gamescope-shdr" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffede7b6c0 (LWP 35453)]
0x000055555558dc6c in ?? ()
(gdb) (EE) could not connect to wayland server
bt
#0  0x000055555558dc6c in  ()
#1  0x000055555558e002 in  ()
#2  0x00007ffff76e1943 in std::execute_native_thread_routine(void*)
    (__p=0x555555adef80)
    at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:104
#3  0x00007ffff73b044b in start_thread (arg=<optimized out>)
    at pthread_create.c:444
#4  0x00007ffff7433e40 in clone3 ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) exit
A debugging session is active.

	Inferior 1 [process 35418] will be killed.

Quit anyway? (y or n) y
[alex@alex-pc ~]$
```
</details>
